Creating a requirements.txt for ReadTheDocs
ReadTheDocs is unable to compile the Connect project due to an error.
This should remove the offending package.

The offending compile error:

```
/usr/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```